# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@v1.1.1

      - name: EC Audit PR
        run: env = { ALWAYS_LINT_ALL_FILES = "false"}
