name: Deploy modpack
on:
  push:
    tags:
      - "R*"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $1}')

      - name: Write manifest
        run: sed -i 's/%MODPACK_VERSION%/${{ steps.get_release.outputs.tag_name }}/g' manifest.json

      - name: Zip Modpack
        run: zip -r modpack.zip *

      - name: Build Server
        uses: henkelmax/build-modpack-server-action@v1.0.0
        with:
          modpack-path: ./modpack.zip
          output-path: ./modpack-server.zip

      - name: Read Changelog
        id: read_changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Changelog_RU.md

      - name: Get Release Type
        id: get_curseforge_release_type
        run: |
          RELEASE_TYPE=$(echo ${{ steps.get_release.outputs.name }} | grep -oE '\[(.*)\]' | sed 's/[][]//g')
          echo ::set-output name=release_type::$RELEASE_TYPE

      - name: Upload to CurseForge
        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
        with:
          api-token: ${{ secrets.CF_API_TOKEN }}
          project-id: '385053'
          modpack-path: './modpack.zip'
          game-version: '6756'
          display-name: 'TFG New Horizons ${{ steps.get_release.outputs.tag_name }}'
          release-type: "release"
