name: Notification on push EN

on:
  release:
    types: [published]

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: SpeeeDCraft/github-to-discord@main
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_EN }}
        DISCORD_USERNAME: GitHub
        DISCORD_AVATAR: https://cdn.discordapp.com/attachments/932122658219360287/983200453938511892/8a9134c7d8e6b822.jpg
        MESSAGE_TITLE: New Version
        MESSAGE_DESCRIPTION: Click on the blue version number above to see Changelog!
        MESSAGE_URL: https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/blob/main/Changelog_EN.md
        MESSAGE_COLOR: 5814783
